[program:nightwatch-agent]
process_name=%(program_name)s
command=php /app/artisan nightwatch:agent
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
startsecs=0
stdout_logfile=/var/log/nightwatch-agent.log
stderr_logfile=/var/log/nightwatch-agent.log
